### ISSUE TITLE
Winston

### ISSUE THREAD

**Issue by nozkray** [Blackhawk-TA/dynoBot#25]
I always get this error whenever I use node main.js 

SyntaxError: C:\Users\clark\Programming\dynoBot-master\cfg\security.json: Unexpected token ` in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\clark\Programming\dynoBot-master\src\utils\logger.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by Blackhawk-TA** [comment]
It looks like your security.json file has an invalid JSON syntax.
It should look like this:
```json
{
	"token": "your discord bot token"
}
```

Make sure to use " instead of ` for strings. If this does not work, please send your security.json **without the original discord token**.

**Comment by nozkray** [comment]
i have my json like this

```json
{
	"token": "token"
	"wolframAlphaAPI": "code"
}
```

**Comment by nozkray** [comment]
now it says

SyntaxError: C:\Users\clark\Programming\dynoBot-master\cfg\security.json: Unexpected token
 in JSON at position 5

**Comment by Blackhawk-TA** [comment]
You forgot a comma after your token. JSON requires several properties to be separated by a comma.
Try this json: 
```json
{
	"token": "token",
	"wolframAlphaAPI": "code"
}
```
